#!/bin/sh

set -e

echo "Removing unneccessary installs..."
rm webkit/debian/gir*
rm webkit/debian/*-doc*
rm webkit/debian/*-dev*

echo "Changing source format to 3.0 (native)..."
echo "3.0 (native)" > webkit/debian/source/format

echo "Patching control file..."
sed -i '/gobject-introspection /d ; /libgirepository1.0-dev /d ; /libfile-copy-recursive-perl,/d' webkit/debian/control
sed -i '/Package: .*-dev/,/^$/d ; /Package: .*-doc/,/^$/d ; /Package: gir.*/,/^$/d' webkit/debian/control

echo "Patching rules file..."
sed -i 's/\(EXTRA_CMAKE_ARGUMENTS =\)$/\1 -DENABLE_INTROSPECTION=OFF -DENABLE_GLES2=ON/' webkit/debian/rules
sed -i 's/ --with gir//' webkit/debian/rules
sed -i 's/\(dh_missing\) --fail-missing$/\1/' webkit/debian/rules
